version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  ApplicationStop:
    - location: stop_compose.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy.sh
      timeout: 600
      runas: root