version: '3.9'
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: backend-container
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    network_mode: "ec2-user_app-network"
